---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Autonomer Wertstoffhof"
keywords:    "Autonomer Wertstoffhof, Recycling, Entsorgung, Abfallwirtschaft, Nachhaltigkeit, Mülltrennung, Umweltschutz, Ressourcenschonung, Müllentsorgung, Wertstoffe, Nachhaltiges Recycling, Umweltfreundliche Entsorgung, Müllvermeidung, Kreislaufwirtschaft, Elektroschrott, Altglas, Altpapier, Plastikrecycling, Umweltbewusstsein, Ökologische Nachhaltigkeit"

## description: "Autonomer Wertstoffhof description"
description: "Erfahren Sie alles über den autonomen Wertstoffhof - ein innovatives Konzept für die Entsorgung von Abfällen und Recyclingmaterialien. Entdecken Sie, wie ein autonomer Wertstoffhof funktioniert, welche Materialien dort entsorgt werden können und wie Sie davon profitieren können. Informieren Sie sich über die Vorteile für die Umwelt und die Gemeinschaft sowie die praktischen Aspekte der Nutzung."

source_link: "https://softwareengel.github.io/autonomer-wertstoffhof/"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: ## UA-49607422-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false

